# Generated by Django 4.0.3 on 2022-03-11 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='pro',
        ),
    ]
