# Generated by Django 4.0.3 on 2022-03-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_rename_user_pro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro',
            name='img',
            field=models.ImageField(upload_to='images'),
        ),
    ]
